### ISSUE TITLE
並びましたイベントが複数回発生する。

### ISSUE THREAD

**Issue by kayhide** [runnable-inc/wonder_cat_factory#12]
http://www.wonder-cat-factory.com/admin/products/28/bids/111

**Comment by kayhide** [comment]
同一ユーザーが同一作品に複数の bid を作れてしまう。
validation だけでは回避できない。
http://guides.rubyonrails.org/v4.2/active_record_validations.html#uniqueness

**Comment by sakahukamaki** [comment]
@kayhide 画面上からの再現って現在も可能ですか？ uniq index張れば終わるような気がしています。

**Comment by kayhide** [comment]
@sakahukamaki このあたりの事情は変わってないので再現するとは思いますが少し手間ですね。
いくつかスレッドを立てて並列で同時にデータを更新するようなスクリプトを書けば再現させやすいかもしれません。
ローカルの開発環境で試してみていただけますか？

> uniq index張れば終わるような気がしています。

実は僕もそんな気がしています。

**Comment by sakahukamaki** [comment]
@kayhide 
コンソール上でバリデーションを無視するようにしたらひとまずデータ上では再現しました。今夜migrationのみのPRを出します。
