### ISSUE TITLE
自動送信されるメールメッセージを修正できるようにしたい

### ISSUE THREAD

**Issue by wonder-cat-factory** [runnable-inc/wonder_cat_factory#13]
ログイン時（ユーザー側、デザイナー側）
※管理者が変更できるのが望ましいが固定文章で問題ないですー。

募集開始時（デザイナー側への）
着列時（ユーザー側、デザイナー側）
行列の人数が目標に達成時（ユーザー側、デザイナー側）
順番が回ってきた時（ユーザー側）

デザイナー側へのメッセージは管理者が修正できる。
ユーザー側へのメッセージはデザイナー、管理者ができる。

ただし、デフォルト文章が入っていて（js等使ってデフォルト表示）
 上書き登録することで修正できるようにする

**Comment by kitaindia** [comment]
ルーティング
管理側
一覧
/admin/emails

修正
/admin/emails/:id/edit

デザイナーのメッセージ
一覧
/emails
/emails/:id/edit

emailだと、送ったメールそのものをさしてるみたいで変かなあ、とりあえずやってみます

**Comment by kitaindia** [comment]
- [ ] 募集開始時メッセージ
- [ ] 着列時メッセージ
- [ ] 行列の人数が目標に達成時
- [ ] 順番が回ってきた時

**Comment by tmiyamon** [comment]
@wonder-cat-factory 
デフォルトで入れたい件名と本文はありますか？
なければ「未設定」となります。
今は「未設定」のまま進めてあとで変更も可能です。

**Comment by kitaindia** [comment]
・デザイナー側に表示する文面設定は完了です。

**Comment by wonder-cat-factory** [comment]
・こちらの件名と本文は検討中ですね。

2017-04-13 18:27 GMT+09:00 Masaki Takehara <notifications@github.com>:

**Comment by kitaindia** [comment]
ユーザー側もマージされたのでこちらはcloseします。
