### ISSUE TITLE
画像アップロード機能修正

### ISSUE THREAD

**Issue by wonder-cat-factory** [runnable-inc/wonder_cat_factory#14]
作品画像アップロード時
ファイル選択と➕ボタンの操作を
間違える可能性があるので
ファイル選択されるまで➕ボタンを
押せないようにするなど対策が欲しい

**Comment by kayhide** [comment]
画像アップロードの UI をまるっと変更しました。
ご確認くださいませ。

**Comment by wonder-cat-factory** [comment]
了解ですー。

2016-11-17 17:23 GMT+09:00 kayhide <notifications@github.com>:

**Comment by wonder-cat-factory** [comment]
河合さん、画像アップロードわかりやすくて、使いやすくてGOODでございます！
アップロード領域のコメントが日本語にすれば問題なしです。あざます。

複数画像アップロードできるようですが
今のところは表示されるの最初の一枚でですよね？

各デザイナーさんページ作る時に使うということですね！

**Comment by kayhide** [comment]
@wonder-cat-factory 
>
アップロード領域のコメントが日本語にすれば問題なしです。

そうかと思いましたが、ちょい手間なので放置しておきました。
さしあたり、これで使ってみてください。

>
複数画像アップロードできるようですが
今のところは表示されるの最初の一枚でですよね？
各デザイナーさんページ作る時に使うということですね！

そういうことです。
表示ページはデザイン絡みなので、そのあたりを更新するときに一緒にやります。

**Comment by wonder-cat-factory** [comment]
ありがとうございます。

2016年11月21日 14:08 kayhide <notifications@github.com>:

**Comment by kayhide** [comment]
イシューの対応自体は完了しましたのでクローズします。
