### ISSUE TITLE
金額欄で税込み、税抜きの表記

### ISSUE THREAD

**Issue by wonder-cat-factory** [runnable-inc/wonder_cat_factory#15]
金額登録時に税込み・税抜きの選択
着列者が参照時に税込みか税抜きかの表記

**Comment by kayhide** [comment]
@wonder-cat-factory 全て税込で扱う、という方針でよいでしょうか？

**Comment by wonder-cat-factory** [comment]
構いせんよー。
そういうルールにしましょか。
金額書く欄に税込みとわかるように
して頂ければ良いです。

**Comment by kayhide** [comment]
了解ですー。

**Comment by kayhide** [comment]
編集画面での表記を「税込価格」にしました。
着列者向けの表記は #17 で対応します。

**Comment by wonder-cat-factory** [comment]
税込価格　確認しました。
取り急ぎ問題ありませーん。
割引や値引き機能とか今後つけたくなりますね。＾＾
