### ISSUE TITLE
脱列できるようにする。

### ISSUE THREAD

**Issue by kayhide** [runnable-inc/wonder_cat_factory#19]

**Comment by kitaindia** [comment]
@kayhide 

いったんPRを作成しました。

【質問】
脱列できなくさせる条件は必要ですか？　（別イシューでやるべきことかもですが）

１.　人数が集まったら脱列不可
２．商品の代金を支払ったら脱列不可
等...

**Comment by kayhide** [comment]
@kitaindia 脱列可なのは、

- 入店（＝支払い）以前

でお願いします。

なので、

- 人数が集まった（= 制作開始後〜入店前）は*脱列可能*
- 支払後（=入店後）は*脱列不可能*

です。

**Comment by kitaindia** [comment]
対応してみました。 詳細はPRに書きます

もう一つ質問があります。

* 支払いのタイミングですが、順番待ちに並んで、accepted_atが更新されて「順番が回ってきました」にボタンが変わってから、支払いボタンがでてくるというイメージでしょうか

ここらへんはまだ仕様未確定な感じでしょうか。

stripeで支払いが行える条件もまだ、実装してなかったですね・・。

**Comment by kayhide** [comment]
入店後の流れについては #30 で検討中ですね。

何を買うかは入店時点では決まっていない、ということになりそうです。
ですので、その時点では支払いはできないでしょうね。

**Comment by kitaindia** [comment]
こちらのissueは完了したのでcloseします。
