### ISSUE TITLE
admin 画面で seller が StripeAccount を持っているか否かを判別したい。

### ISSUE THREAD

**Issue by kayhide** [runnable-inc/wonder_cat_factory#27]

**Comment by kitaindia** [comment]
@kayhide さん
こちらのイシューは、admin/users のリストの一覧画面で「Stripe」みたいな名前の列を一つ足して表示するようにしてほしいということでしょうか

**Comment by kayhide** [comment]
それでよいと思います。

**Comment by kitaindia** [comment]
@kayhide 
対応しました
https://github.com/runnable-inc/wonder_cat_factory/pull/31
