### ISSUE TITLE
出品者が StripeAccount と紐付いてないと支払いでエラーになる。

### ISSUE THREAD

**Issue by kayhide** [runnable-inc/wonder_cat_factory#28]

**Comment by kitaindia** [comment]
@kayhide さん
こちらの対応策ですが、
出品者が作品を登録する際、もしくはアカウント作成時にStripeAccountを作成するという対応はどうでしょうか？
https://github.com/runnable-inc/wonder_cat_factory/issues/27
アカウント作成時に、一緒に作るようにすればこちらの対応も必要なくなるかもしれません

**Comment by kayhide** [comment]
StripeAccount が必要になるのは、はじめて入店を促したあとになります。
ですので、そのタイミングでチェックして、存在しなければ作成する、という方向がよいと思います。
