### ISSUE TITLE
権限とメニューの内容が一致しない

### ISSUE THREAD

**Issue by sakahukamaki** [runnable-inc/wonder_cat_factory#38]
管理者・出品者権限に沿ったメニューが表示されていない。

管理者権限のみ ... 出品者ページ 
![admin](https://cloud.githubusercontent.com/assets/10892953/22505799/9c17d7d8-e8c0-11e6-98cc-4f6c23a716bc.png)

出品者権限のみ ... 管理者ページ、Mailer Preview、Letter Opener 
![seller](https://cloud.githubusercontent.com/assets/10892953/22505798/9c162744-e8c0-11e6-9ff6-edb1108ec493.png)

**Comment by kayhide** [comment]
@sakahukamaki ありがとうございます。
マージしましたのでご確認ください。
問題なければクローズしてしまってくださいませ。

**Comment by sakahukamaki** [comment]
確認しました。クローズします。
