### ISSUE TITLE
Stripe の決済を入れる。

### ISSUE THREAD

**Issue by kayhide** [runnable-inc/wonder_cat_factory#9]
https://stripe.com/connect
https://stripe.com/docs/api/ruby

**Comment by kayhide** [comment]
これがうまくいけば、#3 は不要。

**Comment by kitaindia** [comment]
@kayhide 
@wonder-cat-factory 

作っている部分
・stripeクレジットカード決済のjsのポップアップ組み込み
・出品者のuserアカウントと、stripeのアカウントとの連携

![image](https://cloud.githubusercontent.com/assets/910159/20598109/d026bdee-b28a-11e6-9dbc-14b8d618cc36.png)

![image](https://cloud.githubusercontent.com/assets/910159/20598130/ee8ddda8-b28a-11e6-90aa-c0f3ab5aa2e4.png)

まだの部分
1. クレジットカード入力して決済ボタンを押した際、実際にトランザクションが発生する部分の所
2.出品者側で振込情報等を入れる部分

**Comment by kitaindia** [comment]
プロトタイプでざっくりですが、stripe connectを使用した決済を組み込んでみました。

**Comment by wonder-cat-factory** [comment]
確認しますー。

2016年11月30日(水) 8:55 Masaki Takehara <notifications@github.com>:

**Comment by kayhide** [comment]
基礎的な部分は導入できたのでクローズします。
